name: compasia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.2
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  logger: ^2.0.2+1
  fluttertoast: ^8.2.4
  lottie: ^2.7.0
  flutter_swipe_action_cell: ^3.1.3
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/lotties/
    - assets/blank/

